spring:
  application:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
        generate-ddl: true
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format-sql: true
        show-sql: true
      properties:
        hibernate:
          format_sql: true
